---

- hosts: all
  user: root

  tasks:
  
- include: cldstk-files-update.yml
- include: cldstk-agent_deploy.yml
- include: mysql-server-install.yml
- include: cldstk-mgmt_deploy.yml
- include: cldstk-nfs-server.yml
- include: cldstk-preseed-kvm-systmpl.yml
