---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server


- hosts: db_master
  user: root
  vars_files:
    - ../vars_file.yml

  tasks:
    - name: Configure API to use null
      command: mysql -uroot -p{{ mysql_root_password }} -e "update cloud.configuration set value=NULL where name='integration.api.port';"

- hosts: cldstk_mgmt:cldstk_web
  user: root
  vars_files:
    - ../vars_file.yml

  tasks:
    - name: Restart the cloudstack-management service
      action: service name=cloudstack-management state=restarted

