---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server


- hosts: db_master
  user: root

  tasks:
    - name: Configure API port to use 8096
      command: mysql -uroot -p{{ mysql_root_password }} -e "update cloud.configuration set value=8096 where name='integration.api.port';"

- hosts: cldstk_mgmt:cldstk_web
  user: root

  tasks:
    - name: Restart the cloudstack-management service
      action: service name=cloudstack-management state=restarted


