---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../vars_file.yml

  tasks:
    - name: Stop iptables
      action: service name=iptables state=stopped

    - name: Clean yum repositories
      command: yum clean all

    - name: Install Dependancies
      action: yum name={{ item }} state=installed
      with_items:
        - libselinux-python
    - name: Update cloudstack.repo file for local install
      lineinfile: dest='../resources/cloudstack.repo' regexp='^#?baseurl='
                  line="baseurl=http://{{ ansible_default_ipv4.address }}:8080/acs/rpms/{{ repoversion }}/"
                  state=present
      when: repotype == "Local"

    - name: Update cloudstack.repo file for internet install
      lineinfile: dest='../resources/cloudstack.repo' regexp='^#?baseurl='
                  line="baseurl=http://cloudstack.apt-get.eu/rhel/{{ repoversion }}/"
                  state=present
      when: repotype == "Internet"

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://{{ ansible_default_ipv4.address }}:8080/acs/templates/4.4/systemvm64template-4.4.0-6-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Local" and repoversion == 4.4

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://cloudstack.apt-get.eu/systemvm/4.4/systemvm64template-4.4.0-6-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Internet" and repoversion == 4.4

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://{{ ansible_default_ipv4.address }}:8080/acs/templates/4.3/systemvm64template-2014-01-14-master-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Local" and repoversion == 4.3

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://download.cloud.com/templates/4.3/systemvm64template-2014-01-14-master-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Internet" and repoversion == 4.3

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://{{ ansible_default_ipv4.address }}:8080/acs/templates/4.2/systemvmtemplate-2013-06-12-master-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Local" and repoversion == 4.2

    - name: Update cloudstack-systmpl_preseed.yml file for local install
      lineinfile: dest='../vars_file.yml' regexp='^#?systemtemplate'
                  line='systemtemplate':' http://download.cloud.com/templates/4.2/systemvmtemplate-2013-06-12-master-kvm.qcow2.bz2'
                  state=present
      when: repotype == "Internet" and repoversion == 4.2



- hosts: all
  user: root
  vars_files:
    - ../vars_file.yml

  tasks:
    - name: Install Dependancies
      action: yum name={{ item }}
      with_items:
        - libselinux-python
        - ntp

    - name: Set SELinux to Permissive
      action: selinux policy=targeted state=permissive

    - name: Update /etc/hosts file
      lineinfile: dest=/etc/hosts
                  regexp="^#?{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
                  line="{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
                  state=present
                  backup=yes
      when: hostvars[item]['ansible_default_ipv4']['address'] is defined
      with_items: groups.all

    - name: Stop service NTP
      action: service name=ntpd state=stopped

    - name: Update system time
      command: ntpdate 0.centos.pool.ntp.org
      ignore_errors: yes

    - name: Start service NTP
      action: service name=ntpd state=started

