---

- hosts: cldstk_mgmt
  user: root

  tasks:
    - name: configure api integration so we can get the apikey and secretkey for admin
      command: mysql -uroot -p{{ mysql_root_password }} -e "update configuration set value=8096 where name='integration.api.port';"

    - name: Start the cloudstack-management service
      action: service name=cloudstack-management state=restarted


- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Stop iptables
      command: 





- hosts: cldstk_mgmt
  user: root

  tasks:
    - name: Disable api integration so we can get the apikey and secretkey for admin
      command: mysql -uroot -p{{ mysql_root_password }} -e "update configuration set value='' where name='integration.api.port';"

    - name: Start the cloudstack-management service
      action: service name=cloudstack-management state=restarted
