---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: localhosts
  connection: local
  
  tasks:
    - name: Stop iptables
      action: service name=iptables state=stopped

    - name: Clean yum repositories
      command: yum clean all

- hosts: all
  user: root

  tasks:
    - name: Install Dependancies
      action: yum name={{ item }}
      with_items:
        - libselinux-python
        - ntp
      when: ansible_distribution == 'CentOS'

    - name: Add Cloudstack Repository
      copy: src="../jobs/{{ job_id }}/cloudstack.repo" dest="/etc/yum.repos.d/cloudstack.repo"

    - name: Set SELinux to Permissive
      action: selinux policy=targeted state=permissive
      when: ansible_distribution == 'CentOS'

    - name: Update /etc/hosts file
      lineinfile: dest=/etc/hosts
                  regexp="^#?{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
                  line="{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
                  state=present
                  backup=yes
      when: hostvars[item]['ansible_default_ipv4']['address'] is defined
      with_items: groups.all

    - name: Stop service NTP
      action: service name=ntpd state=stopped
      when: ansible_distribution == 'CentOS'

    - name: Update system time
      command: ntpdate 0.centos.pool.ntp.org
      ignore_errors: yes
      when: ansible_distribution == 'CentOS'

    - name: Start service NTP
      action: service name=ntpd state=started
      when: ansible_distribution == 'CentOS'

    - name: Downloading and enable the EPEL repository definitions.
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
      when: ansible_distribution == 'CentOS'
