---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: mysql_servers
  user: root
  vars_files:
    - ../vars_file.yml

  roles:
    - cldstk-mysql

