---
- name: Stop iptables
  action: service name=iptables state=stopped

- name: Add Cloudstack Repository
  copy: src="../resources/cloudstack.repo" dest="/etc/yum.repos.d/cloudstack.repo"

- name: Clean yum repositories
  command: yum clean all

- name: Install Dependancies
  action: yum name={{ item }}
  with_items:
    - libselinux-python
    - ntp
    - mysql

- name: Set SELinux to Permissive
  action: selinux policy=targeted state=permissive

- name: Stop service NTP
  action: service name=ntpd state=stopped

- name: Update system time
  command: ntpdate 0.centos.pool.ntp.org

- name: Start service NTP
  action: service name=ntpd state=started

- name: Downloading and enable the EPEL repository definitions.
  action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: ansible_distribution == 'CentOS'
  # and ansible_lsb.major_release|int == 6

- name: Install Cloudstack Management RPMS
  action: yum name={{ item }}
  with_items:
    - cloudstack-management
    - cloudstack-usage
    - cloudstack-awsapi
    - cloudstack-common
    - java-1.6.0

- name: Add link for mysql-connector-java.jar.
  action: command ln -s /usr/share/java/mysql-connector-java.jar /usr/share/cloudstack-usage/lib/mysql-connector-java.jar
