---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: cldstk_kvm
  user: root
  serial: 1
  vars_files:
    - vars_file.yml

  tasks:
    - name: Stop iptables
      action: service name=iptables state=stopped

    - name: Clean yum repositories
      command: yum clean all

    - name: Install Dependancies
      action: yum name={{ item }}
      with_items:
        - libselinux-python
        - ntp
        - python-virtinst 
        - qemu-kvm

    - name: Update /etc/hosts file
      lineinfile: dest=/etc/hosts regexp='^#?{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}' 
                  line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}" 
                  state=present
                  backup=yes

    - name: Set SELinux to Permissive
      action: selinux policy=targeted state=permissive

    - name: Start service NTP
      action: service name=ntpd state=started enabled=yes

    - name: Downloading and enable the EPEL repository definitions.
      action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      when: ansible_distribution == 'CentOS'

    - name: Copy cloudstack-setup-agent.py script to /tmp
      copy: src=cldstk-setup-agent.py dest=/tmp

    # - name: Copy cloudstack RPMS
    #   copy: src={{ item }} dest=/tmp
    #   with_items:
    #     - acs-4.2.1-rpms/cloudstack-common-4.2.1-1.el6.x86_64.rpm
    #     - acs-4.2.1-rpms/cloudstack-agent-4.2.1-1.el6.x86_64.rpm

    - name: Add Cloudstack Repository
      copy: src=cloudstack.repo dest=/etc/yum.repos.d/cloudstack.repo

    - name: Install Cloudstack Agent RPMS
      action: yum name={{ item }}
      with_items:
        - cloudstack-common
        - cloudstack-agent

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-common-4.2.1-1.el6.x86_64.rpm state=present

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-agent-4.2.1-1.el6.x86_64.rpm state=present

    - name: Update /etc/libvirt/libvirtd.conf file
      lineinfile: dest=/etc/libvirt/libvirtd.conf
                  regexp='^#?{{ item }}' 
                  backup=yes
                  line='{{ item }}' 
                  state=present   
      with_items:
        - listen_tls = 0
        - listen_tcp = 1
        - tcp_port = "16059"
        - mdns_adv = 0
        - auth_tcp = "none"

    - name: Update /etc/sysconfig/libvirtd file
      lineinfile: dest=/etc/sysconfig/libvirtd
                  regexp='^#?LIBVIRTD_ARGS="--listen"' 
                  backup=yes
                  line='LIBVIRTD_ARGS="--listen"'
                  state=present   

    # - name: Update /etc/cgconfig.conf file
    #   lineinfile: dest=/etc/cgconfig.conf
    #               regexp='^#?LIBVIRTD_ARGS="--listen"' 
    #               backup=yes
    #               line='group virt { 
    #                       cpu { 
    #                         cpu.shares = 9216;
    #                       }
    #                     }'
    #               state=present  

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-awsapi-4.2.1-1.el6.x86_64.rpm state=present

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-usage-4.2.1-1.el6.x86_64.rpm state=present

    - name: Start cgconfig service
      action: service name=cgconfig  state=restarted enabled=yes

    - name: Start libvirtd service
      action: service name=libvirtd state=restarted enabled=yes

    - name: Run Cloudstack agent Configuration scripts
      command: python /tmp/cldstk-setup-agent.py

    - name: Start cloudstack-agent service
      action: service name=cloudstack-agent state=started enabled=yes



