---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: cldstk_web
  user: root
  vars_files:
    - vars_file.yml

  tasks:
    - name: Stop iptables
      action: service name=iptables state=stopped

    - name: Clean yum repositories
      command: yum clean all

    - name: Install Dependancies
      action: yum name={{ item }}
      with_items:
        - libselinux-python
        - ntp
        - mysql

    - name: Set SELinux to Permissive
      action: selinux policy=targeted state=permissive

    - name: Start service NTP
      action: service name=ntpd state=started

    - name: Downloading and enable the EPEL repository definitions.
      action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      when: ansible_distribution == 'CentOS'
      # and ansible_lsb.major_release|int == 6

    # - name: Copy cloudstack RPMS
    #   copy: src={{ item }} dest=/tmp
    #   with_items:
    #     - acs-4.2.1/rpms/cloudstack-management-4.2.1-1.el6.x86_64.rpm
    #     - acs-4.2.1/rpms/cloudstack-usage-4.2.1-1.el6.x86_64.rpm
    #     - acs-4.2.1/rpms/cloudstack-awsapi-4.2.1-1.el6.x86_64.rpm
    #     - acs-4.2.1/rpms/cloudstack-common-4.2.1-1.el6.x86_64.rpm

    - name: Add Cloudstack Repository
      copy: src=cloudstack.repo dest=/etc/yum.repos.d/cloudstack.repo

    - name: Install Cloudstack Management RPMS
      action: yum name={{ item }}
      with_items:
        - cloudstack-management
        - cloudstack-usage
        - cloudstack-awsapi
        - cloudstack-common

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-common-4.2.1-1.el6.x86_64.rpm state=present

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-management-4.2.1-1.el6.x86_64.rpm state=present

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-awsapi-4.2.1-1.el6.x86_64.rpm state=present

    # - name: Install Cloudstack Management RPMS
    #   yum: name=/tmp/cloudstack-usage-4.2.1-1.el6.x86_64.rpm state=present



- hosts: cldstk_web
  user: root
  serial: 1
  vars_files:
    - vars_file.yml

  tasks:
    - name: Run Cloudstack DB Configuration scripts
      command: cloudstack-setup-databases cloud:{{ mysql_root_password }}@{{ master }} --deploy-as=root:{{ mysql_root_password }}

    - name: Run Cloudstack Setup scripts
      command: cloudstack-setup-management

    - name: Start cloudstack-management service
      action: service name=cloudstack-management state=started

    - name: Set cloudstack-management to start at boot time
      action: command chkconfig cloudstack-management on

    - name: Set ntp to start at boot time
      action: command chkconfig ntpd on






