---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars_file.yml

  tasks:
    - name: Stop iptables
      action: service name=iptables state=stopped

    - name: Clean yum repositories
      command: yum clean all

    - name: Install Dependancies
      action: yum name={{ item }} state=installed
      with_items:
        - libselinux-python
    - name: Update /etc/hosts file for local install
      lineinfile: dest='cloudstack.repo' regexp='^#?baseurl=' 
                  line="baseurl=http://{{ ansible_default_ipv4.address }}:3000/acs/rpms/{{ repoversion }}/" 
                  state=present
      when: repotype == "local"
    - name: Update /etc/hosts file for internet install
      lineinfile: dest='cloudstack.repo' regexp='^#?baseurl=' 
                  line="baseurl=http://cloudstack.apt-get.eu/rhel/{{ repoversion }}/" 
                  state=present
      when: repotype == "remote"