---
# ssh-copy-id root@hostname

# cloudstack-mgmt_deploy.yaml
# complete installation of cloudstack-management server

- hosts: all
  user: root
  vars_files:
    - vars_file.yml

  tasks:
    - name: Install Dependancies
      action: yum name={{ item }}
      with_items:
        - libselinux-python
        - ntp

    - name: Set SELinux to Permissive
      action: selinux policy=targeted state=permissive

    - name: Update /etc/hosts file
      lineinfile: dest=/etc/hosts 
                  regexp="^#?{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
                  line="{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}" 
                  state=present
                  backup=yes
      when: hostvars[item]['ansible_default_ipv4']['address'] is defined
      with_items: ${groups.all}
      
