mgmt_primary: cldstkkvm01
master: cldstkkvm01
slave: 
cloud_repl_password: password
mysql_root_password: PaSSw0rd1234
nfs_server: 192.168.78.148
nfs_path: /mnt/volume1/secondary
repotype: Local
repoversion: 4.3
systemtemplate: 